---
title: "Calibration_Tables"
author: "Estee Y Cramer"
date: "10/21/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE, echo = FALSE)
library(lubridate)
library(tidyverse)
<<<<<<< HEAD
library(kableExtra)
=======
library(covidHubUtils)
library(directlabels)
>>>>>>> cdb2361511baf26cc8b612447d3d5a0081296aab
theme_set(theme_bw())
data("hub_locations")
```

```{r read in other files to be used later}
cum_scores <- read_csv("../paper-inputs/20201013-cum-scores.csv") %>%
  filter(location_name %in% datasets::state.name)

inc_scores <- read_csv("../paper-inputs/20201013-inc-scores.csv") %>%
  filter(location_name %in% datasets::state.name)

cum_calibration <- read_csv("../paper-inputs/20201022-cum-calibration.csv") %>%
  left_join(hub_locations, by=c("unit" = "fips")) %>%
  filter(location_name %in% datasets::state.name)

<<<<<<< HEAD
cum_calibration <- read_csv("../paper-inputs/20201022-cum-calibration.csv") 

inc_calibration <-  read_csv("../paper-inputs/20201022-inc-calibration.csv") 
=======
inc_calibration <-  read_csv("../paper-inputs/20201022-inc-calibration.csv") %>%
  left_join(hub_locations, by=c("unit" = "fips")) %>%
  filter(location_name %in% datasets::state.name)

>>>>>>> cdb2361511baf26cc8b612447d3d5a0081296aab
```

```{r cumulative calibration table}
cum_scores_merge <- cum_scores %>%
  left_join(cum_calibration) %>%
  pivot_wider(names_from = "quantile", values_from = "value") %>%
  mutate(calib_95 = ifelse(truth >= `0.025` & truth <= `0.975`, 1, 0),
         calib_50 = ifelse(truth >= `0.25` & truth <= `0.75`, 1, 0))

calibration_scores_cum <- cum_scores_merge %>%
  group_by(model, target) %>%
  summarise(percent_calib50 = round(sum(calib_50)/ n(),2),
            percent_calib95 = round(sum(calib_95) / n(),2)) %>%
    mutate(target = fct_relevel(target, 
                              "1 wk ahead cum death",  "2 wk ahead cum death",  "3 wk ahead cum death",  "4 wk ahead cum death",
                               "5 wk ahead cum death",  "6 wk ahead cum death",  "7 wk ahead cum death",  "8 wk ahead cum death",
                               "9 wk ahead cum death",  "10 wk ahead cum death",  "11 wk ahead cum death",  "12 wk ahead cum death",
                              "13 wk ahead cum death",  "14 wk ahead cum death",  "15 wk ahead cum death",  "16 wk ahead cum death",
                              "17 wk ahead cum death",  "18 wk ahead cum death"))

calibration_scores_cum_table <- calibration_scores_cum  %>%
    pivot_wider(names_from = target, values_from = c(percent_calib50, percent_calib95))

library(kableExtra)
options(knitr.kable.NA = '')
kable(calibration_scores_cum_table) %>%
  kableExtra::add_header_above(c(" ", "50% Calibration" = 18, "95% Calibration" = 18)) %>%
   kable_styling()
```

```{r bar plot cum calibration}
n <- length(unique(calibration_scores_cum$target))
palette <- randomcoloR::distinctColorPalette(n)

ggplot(calibration_scores_cum, aes(fill=target, y=percent_calib50, x=model)) + 
  scale_fill_manual(values = palette)+
    geom_bar(position="dodge", stat="identity")
```

```{r inc calibration table}
inc_scores_merge <- inc_scores %>%
  left_join(inc_calibration) %>%
  pivot_wider(names_from = "quantile", values_from = "value") %>%
  mutate(calib_95 = ifelse(truth >= `0.025` & truth <= `0.975`, 1, 0),
         calib_50 = ifelse(truth >= `0.25` & truth <= `0.75`, 1, 0))

calibration_scores_inc <- inc_scores_merge %>%
  group_by(model, target) %>%
  summarise(percent_calib50 = round(sum(calib_50)/ n(),2),
            percent_calib95 = round(sum(calib_95) / n(),2)) %>% 
  mutate(target = fct_relevel(target, 
                              "1 wk ahead inc death",  "2 wk ahead inc death",  "3 wk ahead inc death",  "4 wk ahead inc death",
                               "5 wk ahead inc death",  "6 wk ahead inc death",  "7 wk ahead inc death",  "8 wk ahead inc death",
                               "9 wk ahead inc death",  "10 wk ahead inc death",  "11 wk ahead inc death",  "12 wk ahead inc death",
                              "13 wk ahead inc death",  "14 wk ahead inc death",  "15 wk ahead inc death",  "16 wk ahead inc death",
                              "17 wk ahead inc death",  "18 wk ahead inc death"),
    horizon = str_split(target, " ", simplify = TRUE),
    horizon = as.numeric(horizon[,1]))

calibration_scores_inc_table <- calibration_scores_inc %>%
    pivot_wider(names_from = target, values_from = c(percent_calib50, percent_calib95)) 

options(knitr.kable.NA = '')
kableExtra::kable(calibration_scores_inc_table) %>%
  add_header_above(c(" ", "50% Calibration" = 18, "95% Calibration" = 18)) %>%
   kable_styling()
```


```{r bar plot incident calibration}
line_labels <- calibration_scores_inc %>%
  group_by(model) %>%
  summarize(max_horizon = max(horizon), last_coera)

ggplot(calibration_scores_inc, aes(fill=target, y=percent_calib50, x=model)) + 
<<<<<<< HEAD
    scale_fill_manual(values = palette)+
    geom_bar(position="dodge", stat="identity")
=======
  geom_bar(position="dodge", stat="identity") + 
  geom_hline(yintercept=.5, linetype=2) +
  theme(axis.text.x = element_text(angle=45, vjust=1, hjust=1))

ggplot(calibration_scores_inc, aes(fill=target, y=percent_calib95, x=model)) + 
  geom_bar(position="dodge", stat="identity") + 
  geom_hline(yintercept=.95, linetype=2) +
  theme(axis.text.x = element_text(angle=45, vjust=1, hjust=1))

calib95 <- ggplot(calibration_scores_inc, aes(x=horizon, y=percent_calib95, color=model, group=model)) + 
  geom_line() + geom_point() + 
  #geom_label(aes(label=model)) +
  geom_dl(aes(label=model), method = list(dl.trans(x = x + 0.2), "last.points", cex = 0.8)) +
  geom_hline(yintercept=.95, linetype=2) +
  scale_y_continuous(name = "Empirical prediction interval coverage", limits = c(0,1)) +
  scale_x_continuous(name = "Forecast horizon (weeks)", breaks=seq(0, 16, by=4), limits=c(1, 20)) +
  guides(color=FALSE) +
  ggtitle("B: 95% prediction interval coverage rates, by model")

calib50 <- ggplot(calibration_scores_inc, aes(x=horizon, y=percent_calib50, color=model, group=model)) + 
  geom_line() + geom_point() + 
  #geom_label(aes(label=model)) +
  geom_hline(yintercept=.5, linetype=2) +
  geom_dl(aes(label=model), method = list(dl.trans(x = x + 0.2), "last.points", cex = 0.8)) +
  scale_y_continuous(name = "Empirical prediction interval coverage", limits = c(0,1)) +
  scale_x_continuous(name = NULL, breaks=seq(0, 16, by=4), limits=c(1, 20)) +
  guides(color=FALSE) +
  ggtitle("A: 50% prediction interval coverage rates, by model")

gridExtra::grid.arrange(calib50, calib95)

>>>>>>> cdb2361511baf26cc8b612447d3d5a0081296aab
```
