---
title: "All_teams_Location_count"
author: "Estee Y Cramer"
date: "10/25/2020"
output: html_document
---

```{r setup, include=FALSE}
## determine model eligibility
library(zoltr)  ## devtools::install_github("reichlab/zoltr")
library(covidHubUtils) ## devtools::install_github("reichlab/covidHubUtils")
library(tidyverse)
library(lubridate)
source("../code/unit_timezero_forecast_complete.R")
```



```{r zoltar-connection-and-data, cache=FALSE, include=FALSE, results="hide"}
#Download score from zoltar. Only 4th inc death target for all models and all target dates up through September 30th

zoltar_connection <- new_connection()
zoltar_authenticate(zoltar_connection, Sys.getenv("Z_USERNAME"), Sys.getenv("Z_PASSWORD"))

the_projects <- projects(zoltar_connection)
project_url <- the_projects[the_projects$name == "COVID-19 Forecasts", "url"]

the_scores <- c("interval_50")

the_models <- c() 
  
the_locations <- c()

the_targets_inc <- c("4 wk ahead inc death")

the_timezeros_inc <- seq(as.Date("2020-04-13"), as.Date("2020-09-30"), by="days")


inc_tmp <- do_zoltar_query(zoltar_connection, project_url =  "https://zoltardata.com/api/project/44/", 
                           is_forecast_query = FALSE, 
                           models = the_models, 
                           units = the_locations, 
                           targets = the_targets_inc, 
                           timezeros = the_timezeros_inc,
                           scores = the_scores)
```


```{r}
# inc_tmp <- do_zoltar_query(zoltar_connection, project_url =  "https://zoltardata.com/api/project/44/", 
#                            is_forecast_query = FALSE, 
#                            models = the_models, 
#                            units = the_locations, 
#                            targets = c("1 wk ahead inc death","2 wk ahead inc death","3 wk ahead inc death","4 wk ahead inc death"), 
#                            timezeros = the_timezeros_inc,
#                            scores = c()) 
# 
# 
# inc_tmp <- inc_tmp %>%
#     mutate(wis = (.01*interval_2+.025*interval_5+.05*interval_10+.1*interval_20+.15*interval_30+.2*interval_40+.25*interval_50+
#             .3*interval_60+.35*interval_70+.40*interval_80+.45*interval_90+.5*interval_100)/12)  %>% 
#     #select(-starts_with("interval")) %>%
#     left_join(hub_locations, by=c("unit" = "fips"))  
```


```{r}
#Select only unique forecasts from each week
inc_tmp_unique <-  inc_tmp %>%
  mutate(sat_fcast_week = as.Date(calc_target_week_end_date(timezero, horizon = 0)) + ifelse(wday(timezero)<=2,0,7) - 7) %>%
  group_by(model, unit, sat_fcast_week) %>%     
  arrange(timezero) %>%    #include arrange so last timezero is selected 
  mutate(forecast_in_wk = row_number(), 
         last_forecast_in_wk = forecast_in_wk == max(forecast_in_wk)) %>%    #number weekly submission
  filter(last_forecast_in_wk) %>%                                            #keep latest weekly submission
  ungroup()

#count number of weeks each team submitted
by_weeks <- inc_tmp_unique %>%
  group_by(model, unit) %>%
  summarise(n_weeks_submit_forecast = n()) %>%
  select(-unit) %>%
  distinct() %>%
  group_by(model) %>%
  filter(n_weeks_submit_forecast == max(n_weeks_submit_forecast))


#Count number of locations each team submitted weekly
num_loc <-inc_tmp_unique %>%
  group_by(model, sat_fcast_week) %>%
  summarise(n_loc = n()) %>%
  right_join(by_weeks) %>%
  mutate(model = as.factor(model))


#Filter out teams that have fewer than 25 locations at every time point
for_loc_figure <- num_loc %>%
  group_by(model) %>%
  filter(max(n_loc) >= 25) %>% #remove models with fewer than 25 locations at all times
  filter(min(sat_fcast_week) <= as.Date("2020-08-29")) %>% #filter models that have start date before end of scored period
  filter(!(model %in% c( "CU-nochange", "CU-scenario_high", "CU-scenario_low", "CU-scenario_mid"))) #remove models that aren't secondary or primary
```

```{r}
for_loc_figure$model <- fct_reorder(for_loc_figure$model, for_loc_figure$n_weeks_submit_forecast) #reorder factors by number of submission weeks
for_loc_figure$model_numeric <- as.numeric(for_loc_figure$model)  #create numeric value for model names

#Plot of locations each model submitted to each week
ggplot(for_loc_figure, aes(y=model, x=sat_fcast_week, fill= for_loc_figure$n_loc)) + 
    geom_tile() +
    geom_text(aes(label=n_loc), size = 5) +
  geom_rect(aes(color="red"),
            xmin=as.Date("2020-05-23") - 3.5, #color of box, start date 3 days before actual date so rectangle covers entire box
            xmax=as.Date("2020-08-29") + 3.5 ,
            ymax= unique(for_loc_figure$model_numeric[for_loc_figure$model == "YYG-ParamSearch"]) + .5,
            ymin= unique(for_loc_figure$model_numeric[for_loc_figure$model == "USACE-ERDC_SEIR"]) - .5,  
            size = 2, fill=alpha("grey",0)) +
    geom_rect(aes(color="red"),
            xmin=as.Date("2020-05-23") - 3.5,
            xmax=as.Date("2020-08-29") + 3.5,
            ymax= unique(for_loc_figure$model_numeric[for_loc_figure$model == "COVIDhub-ensemble"]) + .5, 
            ymin= unique(for_loc_figure$model_numeric[for_loc_figure$model == "IHME-CurveFit"]) - .5,
            size = 2,fill=alpha("grey",0)) +
  scale_fill_steps(low="white", high="blue", name = "Number of Locations") +
   xlab("Saturday of Forecast Submission Week") + ylab(NULL) +
  scale_x_date(date_labels = "%Y-%m-%d", breaks = c(for_loc_figure$sat_fcast_week)) +
   theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 10),
         axis.title.x = element_text(size = 10),
         axis.text.y = element_text(size = 10),
         title = element_text(size = 10)) +
    guides(fill=FALSE, size = FALSE, color = FALSE, alpha = FALSE) +
  ggtitle("Number of locations submitted for incidence death forecasts") 
```


